Lint for head length more than 70 characters

diff --git a/scripts/lint-prepared-commit b/scripts/lint-prepared-commit
--- a/scripts/lint-prepared-commit
+++ b/scripts/lint-prepared-commit
@@ -25,7 +25,7 @@ resolve resolved \
 update updated \
 )
 
-commit_msg=$(grep "^[^#]" "$1"  | head -n 1);
+COMMIT_MSG=$(grep "^[^#]" "$1"  | head -n 1);
 
 # Check whether "RFNO" string still exists (hasn't been checked)
 if [[ ! -z "$(grep 'RFNO' "$1")" ]]; then 
@@ -36,7 +36,7 @@ fi
 
 for bad_word in ${bad_words[*]};
 do
-    if [[ ! -z "$(grep -i "$bad_word\s" <<< $commit_msg)" ]]; then
+    if [[ ! -z "$(grep -i "$bad_word\s" <<< $COMMIT_MSG)" ]]; then
         cp ".git/COMMIT_EDITMSG" "$draft_path"
         loudError "Found \"$bad_word\" in the commit msg head. Aborting Commit."
         exit 1
@@ -46,8 +46,16 @@ done
 # Check for spelling errors
 SPELLING_ERRORS="$(cat $1 | aspell --list)"
 if [[ ! -z $SPELLING_ERRORS ]]; then
-    echo >&2 "---------- SPELLING ERRORS ------------"
+    echo >&2 "------------- SPELLING ERRORS -------------"
     echo >&2 "The following words appear to have been misspelled:"
     echo >&2 "$SPELLING_ERRORS"
-    echo >&2 "---------- SPELLING ERRORS ------------"
+    echo >&2 "------------- SPELLING ERRORS -------------"
+fi
+
+# Check the line length
+if [[ ${#COMMIT_MSG} > 100 ]]; then
+    loudError "Commit heading line length above 100 chars -- Shorten it"
+    exit 1
+elif [[ ${#COMMIT_MSG} > 70 ]]; then
+    loudError "Commit message line length above 72 characters -- You should amend it"
 fi
