Allow a blacklisting of words for the commit subject

diff --git a/scripts/lint-prepared-commit b/scripts/lint-prepared-commit
--- a/scripts/lint-prepared-commit
+++ b/scripts/lint-prepared-commit
@@ -4,6 +4,10 @@
 draft_path=".git/DRAFT_COMMIT_EDITMSG"
 rm "$draft_path" 
 
+# Define a series of "bad words" -- Words that are redundant, or not descriptive enough
+bad_words=(update fix)
+commit_msg=$(grep "^[^#]" "$1"  | head -n 1);
+
 # Check whether "RFNO" string still exists (hasn't been checked)
 if [[ ! -z "$(grep 'RFNO' "$1")" ]]; then 
     cp ".git/COMMIT_EDITMSG" "$draft_path"
@@ -11,8 +15,11 @@ if [[ ! -z "$(grep 'RFNO' "$1")" ]]; then
     exit 1
 fi
 
-if [[ ! -z "$(grep "^[^#]" "$1"  | head -n 1 | grep -i fix)" ]]; then
-    cp ".git/COMMIT_EDITMSG" "$draft_path"
-    echo >&2 "Found \"Fix\" in the commit msg head. Aborting Commit."
-    exit 1
-fi 
+for bad_word in ${bad_words[*]};
+do
+    if [[ ! -z "$(grep -i $bad_word <<< $commit_msg)" ]]; then
+        cp ".git/COMMIT_EDITMSG" "$draft_path"
+        echo >&2 "Found \"$bad_word\" in the commit msg head. Aborting Commit."
+        exit 1
+    fi
+done 
